//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowAuthoring
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Serialization;
    using System.Workflow.ComponentModel.Compiler;
    using System.Drawing;
    using System.Collections;
    using System.Workflow.Activities;
    using System.Workflow.Runtime;
    
    
    public partial class OfficeToAssignmentGroupSRWF : System.Workflow.Activities.SequentialWorkflowActivity
    {
        
        public static System.Workflow.ComponentModel.DependencyProperty OfficeToAssignmentGroupSRScript_GUIDProperty = DependencyProperty.Register("OfficeToAssignmentGroupSRScript_GUID", typeof(System.String), typeof(WorkflowAuthoring.OfficeToAssignmentGroupSRWF));
        
        public string OfficeToAssignmentGroupSRScript_GUID
        {
            get
            {
                return ((string)(base.GetValue(WorkflowAuthoring.OfficeToAssignmentGroupSRWF.OfficeToAssignmentGroupSRScript_GUIDProperty)));
            }
            set
            {
                base.SetValue(WorkflowAuthoring.OfficeToAssignmentGroupSRWF.OfficeToAssignmentGroupSRScript_GUIDProperty, value);
            }
        }
    }
}
